In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [7]:
REPO_PATH = '/home/ah19/runtime-monitoring'
DATASET = 'MNIST'
PREFIX = 'Regularization'
FILENAME_POSTFIX = f"{DATASET}_{PREFIX}"

In [8]:
import sys
sys.path.append(REPO_PATH + '/utilities')
sys.path.append(f'{REPO_PATH}/{DATASET}/trainingModels')


from pathManager import fetchPaths

In [9]:
base = Path(REPO_PATH)
paths = fetchPaths(base, DATASET)

path = paths[DATASET.lower()]
path_dataset = paths['dataset']
path_trainingModels = paths['trainingModels']
path_trainingModels_regularization = paths['trainingModels_regularization']

path

PosixPath('/home/ah19/runtime-monitoring/MNIST')

In [15]:
df = pd.DataFrame()

for i in path_trainingModels_regularization.glob('optunaResults_*'):
    temp = pd.read_csv(i)
    temp['sampler'] = i.name[len('optunaResults_'):]
    df = pd.concat([df, temp])
    
df.reset_index(drop=True, inplace=True)
df.head()

,number,value,datetime_start,datetime_complete,duration,params_L1,params_L2,params_batchsize,params_dropout,params_lr,params_optimizer,state,sampler,system_attrs_cma:generation,system_attrs_cma:n_restarts,system_attrs_cma:optimizer:0,system_attrs_cma:optimizer:1
0,12,0.966,2023-04-08 23:49:41.464367,2023-04-08 23:50:19.869422,0 days 00:00:38.405055,0.0,0.003,32,0.1,0.001,Adam,COMPLETE,TPESampler.csv,NaN,NaN,NaN,NaN
1,54,0.954,2023-04-08 23:58:36.415063,2023-04-08 23:59:08.643904,0 days 00:00:32.228841,0.0,0.016,32,0.5,0.001,Adam,COMPLETE,TPESampler.csv,NaN,NaN,NaN,NaN
2,51,0.940,2023-04-08 23:57:16.117355,2023-04-08 23:57:53.971120,0 days 00:00:37.853765,0.0,0.027,32,0.4,0.001,Adam,COMPLETE,TPESampler.csv,NaN,NaN,NaN,NaN
3,13,0.918,2023-04-08 23:50:19.873139,2023-04-08 23:50:47.568100,0 days 00:00:27.694961,0.0,0.007,32,0.3,0.010,SGD,COMPLETE,TPESampler.csv,NaN,NaN,NaN,NaN
4,47,0.916,2023-04-08 23:56:24.207713,2023-04-08 23:56:57.982089,0 days 00:00:33.774376,0.0,0.037,32,0.4,0.001,Adam,COMPLETE,TPESampler.csv,NaN,NaN,NaN,NaN

In [25]:
df.loc[ np.isclose(df['params_L2'], np.zeros_like(df['params_L2']))].sort_values('value', ascending=False)

,number,value,datetime_start,datetime_complete,duration,params_L1,params_L2,params_batchsize,params_dropout,params_lr,params_optimizer,state,sampler,system_attrs_cma:generation,system_attrs_cma:n_restarts,system_attrs_cma:optimizer:0,system_attrs_cma:optimizer:1
24,39,0.544,2023-04-09 00:15:13.783947,2023-04-09 00:15:17.456090,0 days 00:00:03.672143,0.028,0.0,128,0.5,0.010,SGD,PRUNED,RandomSampler.csv,NaN,NaN,NaN,NaN
42,14,0.492,2023-04-08 23:50:47.570129,2023-04-08 23:50:52.658234,0 days 00:00:05.088105,0.036,0.0,32,0.1,0.001,SGD,PRUNED,TPESampler.csv,NaN,NaN,NaN,NaN
53,45,0.208,2023-04-08 23:56:10.759677,2023-04-08 23:56:14.986252,0 days 00:00:04.226575,0.089,0.0,128,0.2,0.001,SGD,PRUNED,TPESampler.csv,NaN,NaN,NaN,NaN

In [20]:
df.shape

(235, 17)

In [16]:
df.loc[0, 'value']

0.9660000205039978